// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfqcshovcgjiuorczjsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmcWNzaG92Y2dqaXVvcmN6anNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDEwNDEsImV4cCI6MjA3MDUxNzA0MX0.kIZxpUfqf3CAazQhXVwY7g6DJKa2jb682oS8VgPjgtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});